apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-elasticsearch
  name: elasticsearch
  namespace: wazuh
spec:
  ports:
  - name: es-rest
    port: 9200
    targetPort: 9200
  selector:
    app: wazuh-elasticsearch
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  labels:
    app: wazuh-kibana
  name: kibana
  namespace: wazuh
spec:
  ports:
  - name: kibana
    port: 443
    targetPort: 5601
  selector:
    app: wazuh-kibana
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: wazuh-manager
  name: wazuh
  namespace: wazuh
spec:
  ports:
  - name: registration
    port: 1515
    targetPort: 1515
  - name: api
    port: 55000
    targetPort: 55000
  selector:
    app: wazuh-manager
    node-type: master
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-manager
  name: wazuh-cluster
  namespace: wazuh
spec:
  clusterIP: None
  ports:
  - name: cluster
    port: 1516
    targetPort: 1516
  selector:
    app: wazuh-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-elasticsearch
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  clusterIP: None
  ports:
  - name: es-nodes
    port: 9300
    targetPort: 9300
  selector:
    app: wazuh-elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: wazuh-manager
  name: wazuh-workers
  namespace: wazuh
spec:
  ports:
  - name: agents-events
    port: 1514
    targetPort: 1514
  selector:
    app: wazuh-manager
    node-type: worker
  type: LoadBalancer
