apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: https://wazuh-elasticsearch-0.wazuh-elasticsearch:9200
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: elastic-cred
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: elastic-cred
        - name: SERVER_SSL_ENABLED
          value: "true"
        - name: SERVER_SSL_CERTIFICATE
          value: /usr/share/kibana/config/cert.pem
        - name: SERVER_SSL_KEY
          value: /usr/share/kibana/config/key.pem
        - name: WAZUH_API_URL
          value: https://wazuh-manager-master-0.wazuh-cluster
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: wazuh-api-cred
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: wazuh-api-cred
        image: wazuh/wazuh-kibana-odfe:4.2.4
        name: wazuh-kibana
        ports:
        - containerPort: 5601
          name: kibana
        resources:
          limits:
            cpu: 400m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - mountPath: /usr/share/kibana/config/cert.pem
          name: kibana-certs
          readOnly: true
          subPath: cert.pem
        - mountPath: /usr/share/kibana/config/key.pem
          name: kibana-certs
          readOnly: true
          subPath: key.pem
      volumes:
      - name: kibana-certs
        secret:
          secretName: kibana-certs-94k5g5kdc2
