---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-elasticsearch
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-elasticsearch
  serviceName: wazuh-elasticsearch
  template:
    metadata:
      labels:
        app: wazuh-elasticsearch
      name: wazuh-elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: CLUSTER_NAME
          value: wazuh
        - name: NETWORK_HOST
          value: 0.0.0.0
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: wazuh-elasticsearch
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
        image: amazon/opendistro-for-elasticsearch:1.13.2
        name: wazuh-elasticsearch
        ports:
        - containerPort: 9200
          name: es-rest
        - containerPort: 9300
          name: es-nodes
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          capabilities:
            add:
            - SYS_CHROOT
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: wazuh-elasticsearch
        - mountPath: /usr/share/elasticsearch/config/node-key.pem
          name: odfe-ssl-certs
          readOnly: true
          subPath: node-key.pem
        - mountPath: /usr/share/elasticsearch/config/node.pem
          name: odfe-ssl-certs
          readOnly: true
          subPath: node.pem
        - mountPath: /usr/share/elasticsearch/config/root-ca.pem
          name: odfe-ssl-certs
          readOnly: true
          subPath: root-ca.pem
        - mountPath: /usr/share/elasticsearch/config/admin.pem
          name: odfe-ssl-certs
          readOnly: true
          subPath: admin.pem
        - mountPath: /usr/share/elasticsearch/config/admin-key.pem
          name: odfe-ssl-certs
          readOnly: true
          subPath: admin-key.pem
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: elastic-odfe-conf
          readOnly: true
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
          name: elastic-odfe-conf
          readOnly: true
          subPath: internal_users.yml
      initContainers:
      - command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        image: busybox
        name: volume-mount-hack
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: wazuh-elasticsearch
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox
        name: increase-the-vm-max-map-count
        securityContext:
          privileged: true
      volumes:
      - name: odfe-ssl-certs
        secret:
          secretName: odfe-ssl-certs-5bfggtck42
      - configMap:
          name: elastic-odfe-conf-5b9hg68586
        name: elastic-odfe-conf
  volumeClaimTemplates:
  - metadata:
      name: wazuh-elasticsearch
      namespace: es-cluster
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: wazuh-storage
